In [11]:
#importing essential libraries
import numpy as np
import pandas as pd

In [2]:
#loading my netflix dataset
df = pd.read_csv("NFLX.csv")
df

Date        Open        High         Low       Close   Adj Close  \
0     2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
1     2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2     2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   
3     2018-02-08  267.079987  267.619995  250.000000  250.100006  250.100006   
4     2018-02-09  253.850006  255.800003  236.110001  249.470001  249.470001   
...          ...         ...         ...         ...         ...         ...   
1004  2022-01-31  401.970001  427.700012  398.200012  427.140015  427.140015   
1005  2022-02-01  432.959991  458.480011  425.540009  457.130005  457.130005   
1006  2022-02-02  448.250000  451.980011  426.480011  429.480011  429.480011   
1007  2022-02-03  421.440002  429.260010  404.279999  405.600006  405.600006   
1008  2022-02-04  407.309998  412.769989  396.640015  410.170013  410.170013   

        Volume  
0     11896100  
1     12595800  
2      8981500  
3      9306700  
4     16906900  
...        ...  
1004  20047500  
1005  22542300  
1006  14346000  
1007   9905200  
1008   7782400  

[1009 rows x 7 columns]

In [3]:
#deleting date and adj close columns
del df["Date"]
del df["Adj Close"]
df

Open        High         Low       Close    Volume
0     262.000000  267.899994  250.029999  254.259995  11896100
1     247.699997  266.700012  245.000000  265.720001  12595800
2     266.579987  272.450012  264.329987  264.559998   8981500
3     267.079987  267.619995  250.000000  250.100006   9306700
4     253.850006  255.800003  236.110001  249.470001  16906900
...          ...         ...         ...         ...       ...
1004  401.970001  427.700012  398.200012  427.140015  20047500
1005  432.959991  458.480011  425.540009  457.130005  22542300
1006  448.250000  451.980011  426.480011  429.480011  14346000
1007  421.440002  429.260010  404.279999  405.600006   9905200
1008  407.309998  412.769989  396.640015  410.170013   7782400

[1009 rows x 5 columns]

In [4]:
#seperating close column
Y = np.array(df["Close"])
Y

array([254.259995, 265.720001, 264.559998, ..., 429.480011, 405.600006,
       410.170013])

In [5]:
#deleting close column after seperating in Y variable
del df["Close"]
df

Open        High         Low    Volume
0     262.000000  267.899994  250.029999  11896100
1     247.699997  266.700012  245.000000  12595800
2     266.579987  272.450012  264.329987   8981500
3     267.079987  267.619995  250.000000   9306700
4     253.850006  255.800003  236.110001  16906900
...          ...         ...         ...       ...
1004  401.970001  427.700012  398.200012  20047500
1005  432.959991  458.480011  425.540009  22542300
1006  448.250000  451.980011  426.480011  14346000
1007  421.440002  429.260010  404.279999   9905200
1008  407.309998  412.769989  396.640015   7782400

[1009 rows x 4 columns]

In [6]:
#Converting whole dataset into 2-D array
X = df.values
X

array([[2.62000000e+02, 2.67899994e+02, 2.50029999e+02, 1.18961000e+07],
       [2.47699997e+02, 2.66700012e+02, 2.45000000e+02, 1.25958000e+07],
       [2.66579987e+02, 2.72450012e+02, 2.64329987e+02, 8.98150000e+06],
       ...,
       [4.48250000e+02, 4.51980011e+02, 4.26480011e+02, 1.43460000e+07],
       [4.21440002e+02, 4.29260010e+02, 4.04279999e+02, 9.90520000e+06],
       [4.07309998e+02, 4.12769989e+02, 3.96640015e+02, 7.78240000e+06]])

In [7]:
#importing model_selection from sklearn for spliting X and Y into training and testing
from sklearn import model_selection
X_train, X_test ,Y_train,Y_test = model_selection.train_test_split(X,Y, test_size = 0.3) 
X_train,Y_train

(array([[3.78290009e+02, 3.81399994e+02, 3.75559998e+02, 3.73220000e+06],
        [5.49500000e+02, 5.54330017e+02, 5.30030029e+02, 6.34740000e+06],
        [3.53230011e+02, 3.57309998e+02, 3.49010010e+02, 7.97090000e+06],
        ...,
        [2.57290009e+02, 2.61410004e+02, 2.54699997e+02, 6.85520000e+06],
        [5.51130005e+02, 5.56900024e+02, 5.47570007e+02, 4.30980000e+06],
        [2.92750000e+02, 2.95250000e+02, 2.83829987e+02, 1.19321000e+07]]),
 array([380.549988, 530.789978, 351.829987, 371.709991, 323.309998,
        488.929993, 290.299988, 524.890015, 629.76001 , 485.799988,
        314.660004, 518.059998, 611.      , 329.089996, 529.559998,
        312.48999 , 368.329987, 624.940002, 495.98999 , 452.579987,
        658.289978, 503.839996, 351.269989, 312.279999, 548.159973,
        351.600006, 533.030029, 260.579987, 663.840027, 477.579987,
        559.070007, 364.700012, 486.690002, 360.299988, 379.5     ,
        268.149994, 294.149994, 310.839996, 553.409973, 604.55999

In [8]:
print(X_train.shape)
print(Y_train.shape)

(706, 4)
(706,)


In [12]:
#importing Linear Regression model from sklearn for predicting closing stockes of netflix
from sklearn.linear_model import LinearRegression
algo = LinearRegression()
algo.fit(X_train,Y_train)
Y_predict = algo.predict(X_test)
print(Y_predict)
print(Y.shape)

[298.88122884 377.36155366 447.29941881 513.22751124 481.97982072
 309.50210519 383.00439995 491.51743846 361.99928065 314.0975381
 531.81384272 372.48175106 430.94948407 326.43305299 357.83848903
 288.69401802 299.81978123 601.0151806  286.09729484 364.5827556
 279.34354387 349.3823733  495.02168572 546.91464435 530.60621421
 539.20406704 437.98617346 331.9766581  315.08323459 480.82635213
 535.85615546 679.88263537 283.32074564 331.34314079 551.25086178
 529.98287842 343.88599966 518.94232143 364.49062267 564.43513258
 551.5311331  344.68433851 412.42666335 419.20115656 276.52925248
 375.23283304 290.13820653 366.94547154 307.68319227 495.01930638
 436.4884237  416.8330819  464.95203076 495.59644851 284.61982841
 290.72617364 266.72366057 479.31643942 342.06653543 354.48613658
 498.83232921 499.52073754 338.04186143 540.87535963 297.37334294
 529.31333376 241.75963264 481.32542115 359.8155441  350.27973166
 315.64935195 407.78685249 351.94854592 665.78430724 241.84036272
 337.9154663

In [10]:
#printing score of my model
score = algo.score(X_test,Y_test)
score

0.998596344517615